// <auto-generated />
using System;
using System.Collections.Generic;
using AltermedManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AltermedManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250606161258_addNotificationEntity")]
    partial class addNotificationEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AltermedManager.Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("houseNumber")
                        .HasColumnType("integer");

                    b.Property<double>("latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("postalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.Appointment", b =>
                {
                    b.Property<Guid>("appointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<Guid>("doctorId")
                        .HasColumnType("uuid");

                    b.Property<int>("duration")
                        .HasColumnType("integer");

                    b.Property<Guid>("patientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("recordId")
                        .HasColumnType("uuid");

                    b.Property<int>("startSlot")
                        .HasColumnType("integer");

                    b.Property<int>("statusOfAppointment")
                        .HasColumnType("integer");

                    b.Property<int>("treatmentId")
                        .HasColumnType("integer");

                    b.HasKey("appointmentId");

                    b.HasIndex("AddressId");

                    b.HasIndex("patientId");

                    b.HasIndex("startSlot");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.AppointmentSlots", b =>
                {
                    b.Property<int>("slotid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("slotid"));

                    b.Property<DateOnly>("date_of_treatment")
                        .HasColumnType("date");

                    b.Property<Guid>("doctorid")
                        .HasColumnType("uuid");

                    b.Property<string>("endtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("isbooked")
                        .HasColumnType("integer");

                    b.Property<string>("starttime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("slotid");

                    b.ToTable("AppointmentSlots");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.Doctor", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("doctorLicense")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("doctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("doctorSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("placesWorking")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("scheduleId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("specList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.DoctorSchedule", b =>
                {
                    b.Property<Guid>("scheduleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("addressId")
                        .HasColumnType("integer");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("doctorid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("endtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("slotsid")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("starttime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("scheduleid");

                    b.HasIndex("addressId");

                    b.ToTable("DoctorSchedule");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.MedicalRecord", b =>
                {
                    b.Property<Guid>("recordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("appointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("createdBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("patientId")
                        .HasColumnType("uuid");

                    b.Property<int>("recordType")
                        .HasColumnType("integer");

                    b.HasKey("recordID");

                    b.HasIndex("patientId");

                    b.ToTable("MedicalRecord");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.Patient", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<char>("gender")
                        .HasColumnType("character(1)");

                    b.Property<string>("healthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("patientAddressId")
                        .HasColumnType("integer");

                    b.Property<string>("patientEmail")
                        .HasColumnType("text");

                    b.Property<string>("patientID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patientPhone")
                        .HasColumnType("text");

                    b.Property<string>("patientSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("patientAddressId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.PatientFeedback", b =>
                {
                    b.Property<Guid>("feedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("appointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("bodyPart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("newSymptoms")
                        .HasColumnType("text");

                    b.Property<float>("overallStatus")
                        .HasColumnType("real");

                    b.Property<Guid>("patientId")
                        .HasColumnType("uuid");

                    b.HasKey("feedbackId");

                    b.ToTable("PatientFeedbacks");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.PatientRequest", b =>
                {
                    b.Property<Guid>("requestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("answerFromDoctor")
                        .HasColumnType("text");

                    b.Property<Guid>("appointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("doctorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isUrgent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("patientId")
                        .HasColumnType("uuid");

                    b.Property<int>("requestType")
                        .HasColumnType("integer");

                    b.HasKey("requestId");

                    b.HasIndex("patientId");

                    b.ToTable("PatientRequest");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.Recommendation", b =>
                {
                    b.Property<int>("recommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("recommendationId"));

                    b.Property<Guid?>("appointmentId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("isChosen")
                        .HasColumnType("boolean");

                    b.Property<Guid>("patientId")
                        .HasColumnType("uuid");

                    b.Property<string>("reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("recommendationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("recommendedTreatmentId")
                        .HasColumnType("integer");

                    b.Property<string>("source")
                        .HasColumnType("text");

                    b.HasKey("recommendationId");

                    b.HasIndex("appointmentId");

                    b.HasIndex("patientId");

                    b.HasIndex("recommendedTreatmentId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.StoredNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isRead")
                        .HasColumnType("boolean");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("SavedNotifications");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.Treatment", b =>
                {
                    b.Property<int>("treatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("treatmentId"));

                    b.Property<bool>("isAdvanced")
                        .HasColumnType("boolean");

                    b.Property<int>("numOfFeedbacks")
                        .HasColumnType("integer");

                    b.Property<float>("score")
                        .HasColumnType("real");

                    b.PrimitiveCollection<List<string>>("suitCategories")
                        .HasColumnType("text[]");

                    b.Property<string>("treatmentDescription")
                        .HasColumnType("text");

                    b.Property<int>("treatmentDuration")
                        .HasColumnType("integer");

                    b.Property<string>("treatmentGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("treatmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("treatmentPrice")
                        .HasColumnType("numeric");

                    b.HasKey("treatmentId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("firebaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("msgToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.Appointment", b =>
                {
                    b.HasOne("AltermedManager.Models.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("AltermedManager.Models.Entities.Patient", null)
                        .WithMany("appointments")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AltermedManager.Models.Entities.AppointmentSlots", "startAppSlot")
                        .WithMany()
                        .HasForeignKey("startSlot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("startAppSlot");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.DoctorSchedule", b =>
                {
                    b.HasOne("AltermedManager.Models.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("addressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.MedicalRecord", b =>
                {
                    b.HasOne("AltermedManager.Models.Entities.Patient", null)
                        .WithMany("medicalRecords")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.Patient", b =>
                {
                    b.HasOne("AltermedManager.Models.Entities.Address", "patientAddress")
                        .WithMany()
                        .HasForeignKey("patientAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patientAddress");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.PatientRequest", b =>
                {
                    b.HasOne("AltermedManager.Models.Entities.Patient", null)
                        .WithMany("requests")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.Recommendation", b =>
                {
                    b.HasOne("AltermedManager.Models.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("appointmentId");

                    b.HasOne("AltermedManager.Models.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AltermedManager.Models.Entities.Treatment", "RecommendedTreatment")
                        .WithMany()
                        .HasForeignKey("recommendedTreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");

                    b.Navigation("RecommendedTreatment");
                });

            modelBuilder.Entity("AltermedManager.Models.Entities.Patient", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("medicalRecords");

                    b.Navigation("requests");
                });
#pragma warning restore 612, 618
        }
    }
}
