//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltermedManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AltermedManager.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprove or decline new recommendation.
        /// </summary>
        internal static string ApproveOrNotForDoctor {
            get {
                return ResourceManager.GetString("ApproveOrNotForDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New notification.
        /// </summary>
        internal static string NewNotification {
            get {
                return ResourceManager.GetString("NewNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New recommendation received.
        /// </summary>
        internal static string NewRecommendationForPatient {
            get {
                return ResourceManager.GetString("NewRecommendationForPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check new recommendation for patient.
        /// </summary>
        internal static string NewRecommendationToDoctorForApprove {
            get {
                return ResourceManager.GetString("NewRecommendationToDoctorForApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New recommendation created.
        /// </summary>
        internal static string NewRecommendationToDoctorTitle {
            get {
                return ResourceManager.GetString("NewRecommendationToDoctorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request.
        /// </summary>
        internal static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new request from patient.
        /// </summary>
        internal static string NewRequestFromPatientToDoctor {
            get {
                return ResourceManager.GetString("NewRequestFromPatientToDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Response.
        /// </summary>
        internal static string NewResponse {
            get {
                return ResourceManager.GetString("NewResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new response from doctor.
        /// </summary>
        internal static string NewResponseFromDoctorToPatient {
            get {
                return ResourceManager.GetString("NewResponseFromDoctorToPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New recommendation waits approval.
        /// </summary>
        internal static string RecommendationPendingForApprove {
            get {
                return ResourceManager.GetString("RecommendationPendingForApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation was sent..
        /// </summary>
        internal static string RecommendationSent {
            get {
                return ResourceManager.GetString("RecommendationSent", resourceCulture);
            }
        }
    }
}
